### PR TITLE
Added [2.2.5, 2.3.1, 'cache: bundler'] to .travis.yml file

### PR DESCRIPTION
**Pull request by jasnow**
- Added [2.2.5, 2.3.1, 'cache: bundler'] to .travis.yml file. Note that I left 2.2.4 so I was only adding - not changing.

### CODE REVIEW

**Comment by e2** [comment]
Thanks! I never knew the cache is now available for open source projects.

**Comment by e2** [comment]
I'll release shortly.

**Comment by e2** [comment]
Released as 1.3.1.

Let me know if you need anything else.

**Comment by jasnow** [comment]
will do - THANKS!

**Pull request merged**
